### ISSUE TITLE
Funding Request and GAU Expenditures

### ISSUE THREAD

**Issue by mwhenry** [SalesforceFoundation/OutboundFundsModule#131]
I would love if there could be a component similar to _manageExpeditures_ on the Disbursement, that worked instead on the Funding Request.

I'm currently working on a use case where the client wants to integrate with Quickbooks, and they identify their Class (or GAU) when the Funding Request is Approved. This is analogous in NPSP to creating a GAU Allocation when an Opportunity is Won.

As of yet my only workaround is to remove GAU Expenditures from Disbursements and add a new lookup on GAU Expenditures to Funding Requests. While I can meet their requirements, I lose the functionality of the _manageExpenditures_ component.

**Comment by kschaefges** [comment]
This will be created as an internal idea.
