### ISSUE TITLE
Custom Permission Sets

### ISSUE THREAD

**Issue by wcorkill** [SalesforceFoundation/OutboundFundsModule#23]
### Use Cases
Add Permission Sets like other apps have packaged with them. This would allow for easy assignment of access to to the App and/or objects based on these permissions sets.

**Comment by sharireily** [comment]
Reasons - 
Definitely helpful 
Large vs small permission sets - 
How do you assign them? not profiles, extend profiles, modules you can extend permission sets
Trigger to assign etc. - automation to provision
permission set groups - help article - reviewer approver manager 

Are there things that someone shouldn't be seeing 
Restricted view 

- different org might be more specific, but in general there aren't security concerns

Single use case - single user story 
Admin 
- salesforce admin 

User 
- Program officer/ grants manager - application, schedule payments, - Request, Requirements, Disbursement  
- Finance sends payments - Disbursements, GAU Expenditures 
- Reviewer - application review process - across teams - Request, 

- what they don't get 
Delete Request 
Money side is where we tighten controls 

User
-  

Admin 
- disbursement 
-

**Comment by kschaefges** [comment]
This will be created as an idea.  Thanks!
