### ISSUE TITLE
Funding Request Coding

### ISSUE THREAD

**Issue by Nickers3** [SalesforceFoundation/OutboundFundsModule#31]
Create a mechanism to track the funding request coding:

Need to determine if Sustainable Development Goals or Guidestar Impact?

Foundation Center and Guidestart use NTEE Category

Funding Request:
Sustainable Development Goals:
https://en.wikipedia.org/wiki/Sustainable_Development_Goals
Account with formula on Funding Request
NTEE Category - Multi-select

**Comment by kschaefges** [comment]
This will be created as an idea. Thanks!
