### ISSUE TITLE
Enhanced Related Lists

### ISSUE THREAD

**Issue by Nickers3** [SalesforceFoundation/OutboundFundsModule#33]
Outbound Funds is currently configured to the basis related list layouts in Lightning.  Related lists should be enabled as enhanced so all columns in a related list appear.  Page layouts to update - Funding Program, Funding Request, Disbursement and Requirements.

**Comment by Nickers3** [comment]
@sharireily, potential Atlanta Sprint Item

**Comment by kschaefges** [comment]
This will be created as an idea. Thanks!
