### ISSUE TITLE
Update Wiki Images regarding master/detail relationship

### ISSUE THREAD

**Issue by lzmls** [SalesforceFoundation/OutboundFundsModule#35]
Update the images for the NPSP and Core Wiki to reflect the change in the master/detail relationship. Example: https://www.screencast.com/t/QnVoNQSSqBoK

**Comment by Nickers3** [comment]
@SJAmin @wcorkill did either of you create this diagram originally?  If we have the original, this could be a quick fix.

**Comment by Nickers3** [comment]
@sharireily, potential Atlanta Sprint Item

**Comment by kschaefges** [comment]
This image has been updated.
