### ISSUE TITLE
Add Next Requirement Date field on Funding Request

### ISSUE THREAD

**Issue by farahcharania** [SalesforceFoundation/OutboundFundsModule#41]
Similar to the Next Deliverable Date on the Opportunity object, add a Next Requirement Date field on the Funding Request object.

**Comment by sharireily** [comment]
Is this possible? 
- maybe - right now its a lookup so would need to be dlrs
- customizable roll ups? for OBF we build it

Why is this needed? 
- be able to see next date on Funding request 

Solution 
- Document dlrs rollup
sample language for SOQL query 
- Separate project for Customizable rollups ?

**Comment by kschaefges** [comment]
This will be created as an idea.
