### ISSUE TITLE
Add Primary Field to Funding Request Role

### ISSUE THREAD

**Issue by Nickers3** [SalesforceFoundation/OutboundFundsModule#42]
On the Funding Request Role Object, there is no field to state if the role is a primary role.  Some items to consider would be if there is one primary for a particular request or one primary per role on request.  For example, if there is one primary applicant, grant manager, etc.

**Comment by sharireily** [comment]
Create recipe or documentation to describe how to create the link and the primary Funding Request role. 

Can be revisited if use cases become apparent.

**Comment by kschaefges** [comment]
This will be created as an idea.  Thanks!
