### ISSUE TITLE
Disbursement Tab

### ISSUE THREAD

**Issue by Nickers3** [SalesforceFoundation/OutboundFundsModule#49]
Currently there is not a disbursement tab within the core package.  There are use cases in which a user would want to use a disbursement tab to view disbursements this month or for approvals.  Would be good to include this in the disbursements tab as a part of the package.

**Comment by Nickers3** [comment]
@sharireily, potential Atlanta Sprint Item

**Comment by sharireily** [comment]
Who will be creating the disbursement record? 
Grants Manager or DevOps 

For what? 
- Potentially useful for mass actions on list views 
- need tab for integrations 
- list view Hub - Kanban, approvals, changing statuses 
- inline edits 

Why? 
- more efficient

Possible to turn new button off? this is confusing bc creating from tab is confusing if have other ways of creating 
inline editing - record types? a lot clients aren't ready for record types 
- 

Tipping points 
- New Button: This is outside of happy path workflow
- Record Types (for inline edits): This might be too complicated for intro clients 

Decision
 Options: 
1. Default on, but not included in tab
- instructions to add to app 
2. Wait for permission set issue to be addressed ? 

Also add list views? 
Upcoming Disbursements 
Scheduled next 30 days
past due Disbursements

**Comment by kschaefges** [comment]
Many of these were created as reports in the package.
