### ISSUE TITLE
Double-clicking the Save button within the Create Disbursements component results in duplicate disbursement records

### ISSUE THREAD

**Issue by jamesbsfdc** [SalesforceFoundation/OutboundFundsModule#81]
### Summary of the Issue

The Funding Request object contains a Lightning Component action called 'Create Disbursements'. This component allows a user to easily calculate and mass create disbursement records for a funding request.

If a user double-clicks, instead of single-clicks, the Save button it will result in duplicate Disbursement records being created. This also allows a user to bypass the validation in the component itself meant to prevent a user from creating Disbursements which total more than the awarded amount of the Funding Request record.

### Steps to Replicate

- Create a Funding Request with a value >1 in Awarded Amount
- Click Create Disbursements component, click Calculate, and then double-click the Save button
- Observe that double the intended Disbursement records are created

### Workaround

- Ensure users single-click rather than double-click the Save button

**Comment by kschaefges** [comment]
This [WI](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B00000095oEJIAY/view) has been completed.
